pattern_name: disease realized in response to environmental exposure

pattern_iri: http://purl.obolibrary.org/obo/mondo/patterns/realized_in_response_to_evironmental_exposure.yaml

description: 'This pattern is used for a disease, where the cause of the disease is
  an exposure to an environmental stimulus (using ECTO exposure terms) or a medical action, such as a therapeutic treatment (using MAxO terms).
  Note that this pattern does not include infectious disease or classes that would include an organism, virus or viroid. 
  Rather it includes exposures to chemicals (includng drugs), or mixtures.

  Examples: [chemically-induced disorder](http://purl.obolibrary.org/obo/MONDO_0029001),
  [alcohol amnestic disorder](http://purl.obolibrary.org/obo/MONDO_0021702), [alcoholic
  polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0006645), [chemotherapy-induced alopecia](http://purl.obolibrary.org/obo/MONDO_0005483) 
  (26 total)'

contributors:
- https://orcid.org/0000-0002-6601-2165
- https://orcid.org/0000-0001-5208-3432

classes:
  disease: MONDO:0000001
  exposure event: ExO:0000002

relations:
  realized in response to: RO:0009501

annotationProperties:
  exact_synonym: oio:hasExactSynonym
  related_synonym: oio:hasRelatedSynonym

vars:
  disease: '''disease'''
  exposure: '''exposure event'''

name:
  text: '%s realized in response to %s'
  vars:
  - disease
  - exposure

def:
  text: Any %s that is realized in response to a %s
  vars:
  - disease
  - exposure

equivalentTo:
  text: '%s and (''realized in response to'' some %s)'
  vars:
  - disease
  - exposure
